### PR TITLE
CBL-4375: Opening the upgraded database from 2.8 to 3.1 is slow

### PR DESCRIPTION
**Pull request by jianminzhao**
Compared with 2.8, we added a process of startHousekeeping to keep track of expired documents. To do it, we need to find out the closest exipration time, by SQL query, SELECT MIN(expiration) from kv_default". It turned out it's quite expensive as most docs do not have expiration field (= SQLite NULL). By passing this fact to the query, we got return nearly instantly.

Ported from release/lithium, CBL 4325

### CODE REVIEW

**Comment by bmeike** [comment]
I cannot approve this.  It need approval from someone who knows the codebase

**Comment by jianminzhao** [comment]
Understood. It's currently blocked by the PR validation

**Comment by borrrden** [comment]
Hmmm the PR validation here is not encouraging

**Review by pasin — APPROVED** [review]

**Comment by jianminzhao** [comment]
I created a separate ticket to track the first-time slowness, [CBL-4377](https://issues.couchbase.com/browse/CBL-4377)

**Review by bmeike — APPROVED** [review]

**Pull request merged**
