### PR TITLE
Update couchbase-lite-core-black-duck-manifest.yaml

### PR DESCRIPTION
**Pull request by borrrden**

### CODE REVIEW

**Comment by jianminzhao** [comment]
All tests tagged [.VectorSearch] are passed with this PR.

**Review by jianminzhao — APPROVED** [review]

**Comment by jianminzhao** [comment]
@borrrden I have tentatively fixed the test, "DataFile Encryption" according to my understanding of the intent of delete statement. I put my comment there. Please review it.

**Comment by borrrden** [comment]
I don't understand why so much stuff made it into this simple PR

**Comment by jianminzhao** [comment]
Yes, this is quite an unusual situation. As this PR is in outstanding, these two commits are made into the master branch, 374d485e (SQLite carray extension) and bb7d1678 (API to check if a vector index is trained or not). The former commit is very big. This PR is very simple, but because the master branch has some big changes, I decided to merge master branch into this PR on my local machine so that the PR can have trivial (squash) merge to master. During this process, two problems emerged. First, 374d485e did not bring in the latest SQLiteCpp (which is important) and, second, bb7d1678 broke a test. That's why there followed several commits after the merge.

**Pull request merged**
