### PR TITLE
Remove bitcode from iOS builds

### PR DESCRIPTION
**Pull request by borrrden**

### CODE REVIEW

**Comment by borrrden** [comment]
Need some attention from @Pasin first for Xcode stuff.  Perhaps an update is all that is needed but somehow bitcode is getting forced on for the overall build, which then complains about the lack of bitcode for the overall build....

**Comment by borrrden** [comment]
Actually it looks like upgrading Xcode will do the trick here.  I confirmed things build fine on Xcode 14.2 without any more changes

**Review by pasin — APPROVED** [review]
When using XCode 14, this will be perfectly correct.

**Review by pasin — APPROVED** [review]
When using XCode 14, this will be perfectly correct.

**Review by jianminzhao — APPROVED** [review]

**Pull request merged**
