### PR TITLE
Enable iOS support in PublicKey.hh

### PR DESCRIPTION
**Pull request by pasin**
* Made iOS support PERSISTENT_PRIVATE_KEY_AVAILABLE
* Fixed PublicKey+Apple to support both iOS (10.0+) and MacOS.
* Tested manually from CBL side on iOS 13.4.1 (Simulator and Device).
* Plan to test on all supported iOS and MacOS versions on the AWS device farm when the device farm permission is granted.

CBL-860, CBL-861

### CODE REVIEW

**Comment by pasin** [comment]
Tests in PR validation failed but they don't seem to be related to the PR.

```
/var/lib/jenkins/mobile/workspace/eline_couchbase-lite-core_PR-956/couchbase-lite-core/LiteCore/tests/../../Replicator/tests/ReplicatorAPITest.hh:304: FAILED:

  CHECK( status.error.code == 0 )
with expansion:
  5 == 0
```

**Comment by pasin** [comment]
The MacOS Deployment target is set to 10.12 [here](https://github.com/couchbase/couchbase-lite-core/blob/master/Xcode/xcconfigs/Project.xcconfig#L28) so I didn't do the explicit check in the code. Is that the right place to check for the MacOS deployment target?

**Comment by borrrden** [comment]
This is at odds with our [docs](https://docs.couchbase.com/couchbase-lite/current/swift.html#supported-versions) which say we need to go back to 10.11 (10.9 and 10.10 to be removed in 2.8)

**Comment by pasin** [comment]
So which one is correct. CBL iOS Master branch also sets the target version to 10.12 (2.7.0 set to 10.11).

**Comment by borrrden** [comment]
Don't ask me, I'm just the messenger :)

**Comment by pasin** [comment]
Just confirm with @rajagp 10 times that we will do 10.12+ in 2.8.0. We will list 10.12 as a deprecating version.

**Comment by pasin** [comment]
BTW, I did add macOS 10.12 check. Please review.

**Comment by borrrden** [comment]
Looks good except for the error message only says iOS 10 right?

**Comment by pasin** [comment]
I will update the message. Thanks for reviewing.

**Pull request merged**
