### PR TITLE
CBL-4238 : Create SecTrust with certificate chain

### PR DESCRIPTION
**Pull request by pasin**
* Ported the fix from release/3.1 branch (91f5b72a4cde239b3f759b39748f355b62b7278b), which is the fix for CBL-4237.

* Instead of creating the SecTrust with just a leaf cert, create it with the cert chain received from the server.

* Updated `sockpp` submodule to get the fix that passes the cert chains instead of just the leaf cert.

### CODE REVIEW

**Review by bmeike — COMMENTED** [review]
Looks good to me but someone who knows what they are talking about will have to approve it.

**Comment by pasin** [comment]
I'm waiting for the PR validation to be done before assigning the reviewers.

**Review by borrrden — APPROVED** [review]

**Comment by pasin** [comment]
I'm waiting for the sockpp branching decision to be made before merging in case that I need to update the sockpp submodule.

**Comment by pasin** [comment]
I updated the sockpp submodule pointing to the top of couchbase-master branch.

**Review by borrrden — APPROVED** [review]

**Pull request merged**
