### PR TITLE
CBL-4175: Errors from the encryptor callback should cause the checkpo…

### PR DESCRIPTION
**Pull request by jianminzhao**
…int to move past it

### CODE REVIEW

**Comment by bmeike** [comment]
Shouldn't this target the release/lithium branch?

**Review by pasin — APPROVED** [review]

**Review by pasin — COMMENTED** [review]
~~It would be good if we have a test that tests this logic without going through the replicator. All tests are also passed without the fix so I think at least we need a test that tests the issue?~~

**Comment by jianminzhao** [comment]
Right now, after this PR, in terms of the code, lithium and helium are matched. Perhaps we can add tests in postHelium

**Comment by jianminzhao** [comment]
I answered to wrong context. For this PR, yes, we have test cases.

**Pull request merged**
