### PR TITLE
CBL-3489 : excess BLIPIO warning messages of "couldn't find any messa…

### PR DESCRIPTION
**Pull request by jianminzhao**
…ges to process"

Removed the warning for it's not that useful.

### CODE REVIEW

**Comment by borrrden** [comment]
This is an early return, so I assert that SOMETHING should be logged.  If it's noisy it can be moved to a more verbose level. If it is still noisy, the correct course of action is to find out why.

**Review by borrrden — COMMENTED** [review]
See my above comment

**Comment by jianminzhao** [comment]
I studied why. There are two cases,
  void _onWebSocketMessages(int gen =actor::AnyGen) {
              auto messages = _incomingFrames.pop(gen);
              if (!messages) {
                  warn("onWebSocketMessages couldn't find any messages to process");
                  return;
              }
(1) if gen == AnyGen. which only occurs with _close(). Most of time, there is no messages in the queue. It is quite normal.
(2) if gen != AnyGen. This is the normal case when an item is pushed to ActorBatcher. In this case, it should never happen. It's almost like assertion failure.
When running the cpptests, all occurrences are due to (1). It's very normal the queue is empty.

**Comment by jianminzhao** [comment]
Perhaps we should keep the warning when it is not called from BLIPIO::_close(), or, when gen != actor::AnyGen ?

**Review by borrrden — COMMENTED** [review]
I'd definitely prefer to have something there.  Almost universally I want to follow the rule that if we return early from a method, we log something.  If it is too noisy then the conditions of the log can be altered, or alternatively if the return early is the more frequent path then log something if the long path is taken.  Just bread crumbs to let us easily follow the path of the code via logs.

**Review by borrrden — APPROVED** [review]

**Pull request merged**
