### PR TITLE
CBL-5745: Add an API to check if a vector index is trained or not

### PR DESCRIPTION
**Pull request by borrrden**

### CODE REVIEW

**Comment by bmeike** [comment]
Tests failing?  Does that need to be addressed?

**Comment by borrrden** [comment]
That's all fixed up now

**Review by bmeike — COMMENTED** [review]
Many thanks for adding this.  It's a big help.

Do you think it would be helpful to have a comment that explained what the test *does* do, as well as what it doesn't do?  I worry that when it breaks, the next person won't understand how to fix it.

**Comment by bmeike** [comment]
Thanks a bunch for sorting those tests.  Love me a green checkmark.

**Review by jianminzhao — APPROVED** [review]

**Comment by borrrden** [comment]
Oh right the comments about what tests do!  I forgot it even though I was the one that suggested doing it.  It's always a good idea so I will add it.

**Pull request merged**
