### PR TITLE
CBL-4584 : Update sockpp submodule

### PR DESCRIPTION
**Pull request by pasin**
Updated sockpp submodule to pick up the fix that translates ECONNABORTED as MBEDTLS_ERR_NET_CONN_RESET.

### CODE REVIEW

**Comment by pasin** [comment]
There is one test failure (Persistent cert chain) in PR Validation on Mac but it's not related to this PR.

```
[2023-06-06T18:32:10.632Z] -----------------------------------------------------------------------------------------------------------------------
[2023-06-06T18:32:10.632Z] Persistent cert chain
[2023-06-06T18:32:10.632Z] -----------------------------------------------------------------------------------------------------------------------
[2023-06-06T18:32:10.632Z] /Users/mobile/jenkins/mobile/workspace/line_couchbase-lite-core_PR-1803/Crypto/CertificateTest.cc:311
[2023-06-06T18:32:10.632Z] .......................................................................................................................
[2023-06-06T18:32:10.632Z] 
[2023-06-06T18:32:10.632Z] /Users/mobile/jenkins/mobile/workspace/line_couchbase-lite-core_PR-1803/Crypto/CertificateTest.cc:311: FAILED:
[2023-06-06T18:32:10.632Z]   {Unknown expression after the reported line}
[2023-06-06T18:32:10.632Z] due to unexpected exception with message:
[2023-06-06T18:32:10.632Z]   Couldn't add a certificate to the Keychain (SecItemAdd returned -25299)
```

**Comment by jianminzhao** [comment]
In general, we cannot merge it. Does it only fail on that particular Mac, or it would also fail on release Jenkins' pipeline?

**Comment by pasin** [comment]
I do not intend to fix the issue as it's not related to this PR.

**Comment by pasin** [comment]
OK, restarting made the PR validation pass.

**Review by jianminzhao — APPROVED** [review]

**Pull request merged**
