### PR TITLE
Compile LiteCore with sqlcipher

### PR DESCRIPTION
**Pull request by borrrden**

### CODE REVIEW

**Comment by snej** [comment]
Is this going to affect the iOS Obj-C build? I don't know if we want to add SQLCipher to that, as it'll increase the binary size by about 1MB. If not, looks good to me.

**Comment by borrrden** [comment]
Without it lite core will simply crash on iOS 9 though.

**Comment by borrrden** [comment]
That being said it doesn't look like I switched the xcodeproject.

**Comment by snej** [comment]
> Without it lite core will simply crash on iOS 9 though.

Oh right, I forgot that iOS 9's SQLite is too old.

**Comment by snej** [comment]
Do you know why Github shows the entire contents of the CMakeLists.txt files as changed? Maybe you changed the line-break character?

**Comment by borrrden** [comment]
I probably did.  Git loves messing with me on that.  If you are curious then I bet I can rebase this.

**Comment by snej** [comment]
It would be good to get this merged. It looks fine to me, so you can push it after rebasing without a review.

**Pull request merged**
