### PR TITLE
CBL-4376: (Helium port) formatWithCollection thread safety

### PR DESCRIPTION
**Pull request by callumbirks**
Helium port of CBL-4368.

Make formatWithCollection thread-safe.
Change _formatCache to unordered_set.
Add timeout to ReplicatorLoopbackTest.

### CODE REVIEW

**Review by bmeike — CHANGES_REQUESTED** [review]
This cannot go into 3.1 as is.  There is no Crit/Block bug that requires it.
It can totally go into 3.2 but unless there is a clear reason to put it in 3.1, nope....

**Comment by jianminzhao** [comment]
We need this to make Core thread-safe. We observed some occurrences of racing.

**Comment by callumbirks** [comment]
@bmeike The issue that's solved with this change is: There's potential of undefined behaviour if two threads try to log the same thing at roughly the same time. This was the bug causing ReplicatorLoopbackTest to fail consistently. It would probably be less likely to be hit in production, but it's still an issue.

**Review by jianminzhao — APPROVED** [review]

**Comment by borrrden** [comment]
It's more of a procedural thing.  The port needs its own ticket first that can be approved to go into 3.1.

**Review by borrrden — CHANGES_REQUESTED** [review]
The code is fine but the title, commit, etc needs to be changed to a Helium specific ticket.

**Comment by jianminzhao** [comment]
This is a Helium specific ticket. The Beryllium ticket is 4368

**Review by borrrden — APPROVED** [review]
Be sure to not put the beryllium ticket number as-is into the commit message.  Also add the helium ticket number to the commit title when squashing.

**Review by pasin — APPROVED** [review]

**Review by bmeike — APPROVED** [review]
This patch fixes a bug introduced after RC1 in PR https://github.com/couchbase/couchbase-lite-core/pull/1726

**Pull request merged**
