### PR TITLE
Windows sometimes uses EWOULDBLOCK instead of WSAEWOULDBLOCK

### PR DESCRIPTION
**Pull request by ionutcosminmihaipfa**
Related to https://github.com/couchbase/couchbase-lite-core/issues/944

### CODE REVIEW

**Comment by borrrden** [comment]
I think your fork is fooling the PR validation process by being so far behind the actual master branch (GH indicates 68 commits behind and there have been some EE changes since then that are incompatible).  Any chance you could get a branch on your fork that is in line with the current, or fairly recent, HEAD of master here?

**Review by borrrden — CHANGES_REQUESTED** [review]
PR itself looks ok, but see above comment.

**Comment by ionutcosminmihaipfa** [comment]
> 
> 
> I think your fork is fooling the PR validation process by being so far behind the actual master branch (GH indicates 68 commits behind and there have been some EE [closed source] changes since then that are incompatible). Any chance you could get a branch on your fork that is in line with the current, or fairly recent, HEAD of master here?

Done

**Review by borrrden — APPROVED** [review]
Great!  PR validation now shows green.

**Pull request merged**
