### PR TITLE
CBL-3448: Manage mutable members of repl::Options

### PR DESCRIPTION
**Pull request by velicuvlad**
- Moved all mutables under `Mutables` struct
- Updated use/calls to reflect the struct change

### CODE REVIEW

**Review by callumbirks — COMMENTED** [review]
LGTM, seems like it does what the ticket asks. I'm not 100% on understanding exactly what the ticket needs though, so I can't say for sure.

**Comment by borrrden** [comment]
I remember asking for this ticket, and what I imagined was that the mutable members were moved to the replicator itself, so that was the options could be purely const and never need to be modified.  Is that something that would be possible?

**Comment by borrrden** [comment]
Also please avoid making merge commits inside of PRs.  Rebase if needed.

**Review by borrrden — APPROVED** [review]
This is a step in the right direction, but as discussed the next step is likely time consuming and not worth focusing on at the moment so other work should be prioritized.

**Review by pasin — APPROVED** [review]

**Pull request merged**
