### PR TITLE
CBL-2532: Assertion failure when stopping replicator while replicator…

### PR DESCRIPTION
**Pull request by jianminzhao**
… is connecting

### CODE REVIEW

**Comment by borrrden** [comment]
Context?

**Comment by jianminzhao** [comment]
Both start and stop are asynchronous. Start moves to connect, and stop moves to close. So, assertion, Assert(_state < State::connecting) may not hold. It should be either State::unconnected or closed. In the case "closed," _peer will NULL.

**Comment by borrrden** [comment]
How is the peer related to this?  I noticed the _peer non-null assertion moved from connect to _connect

**Comment by jianminzhao** [comment]
From connection() to _connect(), it jumps a thread. We don't need to assert here. We assert in the worker's thread queue where _state is changed.

**Review by borrrden — APPROVED** [review]

**Pull request merged**
