### PR TITLE
use travis for testing linux build on Ubuntu 14.04.5 LTS

### PR DESCRIPTION
**Pull request by Dushistov**
- fix build_cmake/scripts/build_unix.sh to return not 0 on error

### CODE REVIEW

**Comment by Dushistov** [comment]
After fix of #592 build stills failed, at now because of a36949f1d648287abb6fb5f2180d1b1128e6cab3 :

```c++
diff --git a/Replicator/tests/ReplicatorLoopbackTest.cc b/Replicator/tests/ReplicatorLoopbackTest.cc
index 548ef3a6..fa8dfdc2 100644
--- a/Replicator/tests/ReplicatorLoopbackTest.cc
+++ b/Replicator/tests/ReplicatorLoopbackTest.cc
@@ -12,6 +12,7 @@
 #include "Database.hh"
 #include "PrebuiltCopier.hh"
 #include <chrono>
+#include "betterassert.hh"
 
 using namespace litecore::actor;
 
@@ -778,7 +779,8 @@ TEST_CASE_METHOD(ReplicatorLoopbackTest, "Push Validation Failure", "[Push]") {
     auto pullOptions = Replicator::Options::passive();
     atomic<int> validationCount {0};
     pullOptions.callbackContext = &validationCount;
-    pullOptions.pullValidator = [](FLString docID, FLDict body, void *context)->bool {
+    pullOptions.pullValidator = [](FLString docID, C4RevisionFlags flags, FLDict body, void *context)->bool {
+        assert_always(flags == 0);      // can't use CHECK on a bg thread
         ++(*(atomic<int>*)context);
         return (Dict(body)["birthday"].asstring() < "1993");
     };
``` 

looks like library and test code build with `NDEBUG` and without `NDEBUG` correspondingly. 

So I suggest use travis CI to check linux build, it is free for public repositories,
but you need to login to https://travis-ci.org .

In this PR I add build against ubuntu 14 lts, with clang-7.

It is failed because of a36949f1d648287abb6fb5f2180d1b1128e6cab3,
you can see full log here:

https://api.travis-ci.org/v3/job/448020342/log.txt

**Comment by snej** [comment]
I fixed the assert_always issue in Fleece commit ef619cff yesterday; sorry about that.

**Comment by snej** [comment]
FYI, we have our own internal CI using Jenkins, including a [build for Android](http://mobile.jenkins.couchbase.com/view/Core_Based_Builds/job/couchbase-lite-core-android/), but no Ubuntu builds. It took us a while to realize the build was broken, because a typo in the Jenkins config was causing the emails to fall on the floor.

Having Travis too seems like a good idea, esp. since it seems to turn up some build problems that don't happen on Android, even though Android is Linux (right?)

**Comment by snej** [comment]
@borrrden, the changes look good to me, but you're more in tune with Linux and CMake, so could you double-check, and merge if it's ok? Then we can add our own Travis build.

**Pull request merged**
