### PR TITLE
Updated Catch2 to v3.7.1, from v2.13.8

### PR DESCRIPTION
**Pull request by snej**
- Catch itself is in Fleece, along with helper code. This PR depends on https://github.com/couchbase/fleece/pull/240
- Changed `numberOfOptions` constants to use `constexpr`.
- Made a few improvements to test classes as I went through them.
- Some tests were not testing all configurations.
- The old implementation of N_WAY_TEST_CASE_METHOD was a kludge andwould skip SECTIONs in options other than 0; the new one doesn't. This turned up a bug in c4ObserverTest.cc, which I fixed.
- ReplicatorLoopbackTest used a different technique to do multi-way tests, for some reason. I changed it to use the regular N_WAY..  macro.
- VectorRecordTest wasn't being built by CMake, oops! Fixed that.

### CODE REVIEW

**Comment by snej** [comment]
The only remaining problem is that, on Windows, CppTests always hangs during "Continuous Fast Push". Ordinarily the test would time out after 5 minutes, so I think this is a deadlock on ReplicatorLoopbackTest's mutex. @borrrden, if you could check out this PR and run the Windows tests, could you grab a thread dump?

**Comment by borrrden** [comment]
The test doesn't hang when I run it

**Comment by borrrden** [comment]
OK a different one hung when I ran the entire suite and here is the result.  

The destructor of ReplicatorLoopbackTest is hung on waiting for `_parallelThread`:

```c++
~ReplicatorLoopbackTest() override {
    if ( _parallelThread ) _parallelThread->join(); // <---
    _replClient = _replServer = nullptr;
    C4Error error;
    REQUIRE(c4db_delete(db2, WITH_ERROR(&error)));
    c4db_release(db2);
}
```

`_parallelThread` is waiting on a mutex for logging of all things....

```
>	CppTests.exe!litecore::LogDomain::vlog(litecore::LogLevel level, const litecore::Logging * logger, bool doCallback, const char * fmt, char * args) Line 433	C++
 	CppTests.exe!litecore::Logging::_logv(litecore::LogLevel level, const char * format, char * args) Line 695	C++
 	CppTests.exe!litecore::DataFile::_logVerbose(const char * format, ...) Line 180	C++
 	CppTests.exe!litecore::SQLiteKeyStore::set(const litecore::RecordUpdate & rec, litecore::KeyStore::SetOptions flags, litecore::ExclusiveTransaction & __formal) Line 359	C++
 	CppTests.exe!litecore::BothKeyStore::set(const litecore::RecordUpdate & rec, litecore::KeyStore::SetOptions flags, litecore::ExclusiveTransaction & t) Line 60	C++
 	CppTests.exe!litecore::RevTreeRecord::save(litecore::ExclusiveTransaction & transaction) Line 195	C++
 	CppTests.exe!litecore::TreeDocument::save(unsigned int maxRevTreeDepth) Line 320	C++
 	CppTests.exe!litecore::TreeDocument::saveNewRev(const C4DocPutRequest & rq, const litecore::Rev * newRev, bool reallySave) Line 573	C++
 	CppTests.exe!litecore::TreeDocument::putExistingRevision(const C4DocPutRequest & rq, C4Error * outError) Line 529	C++
 	CppTests.exe!litecore::CollectionImpl::putDocument(const C4DocPutRequest & rq, unsigned __int64 * outCommonAncestorIndex, C4Error * outError) Line 260	C++
 	CppTests.exe!c4coll_putDoc::__l2::<lambda_1>::operator()() Line 289	C++
 	CppTests.exe!litecore::tryCatch<C4Document *,`c4coll_putDoc'::`2'::<lambda_1>>(C4Error * outError, c4coll_putDoc::__l2::<lambda_1> fn) Line 56	C++
 	CppTests.exe!c4coll_putDoc(C4Collection * coll, const C4DocPutRequest * rq, unsigned __int64 * outCommonAncestorIndex, C4Error * outError) Line 290	C++
 	CppTests.exe!C4Test::createConflictingRev(C4Collection * collection, FLSlice docID, FLSlice parentRevID, FLSlice newRevID, FLSlice body, unsigned char flags) Line 380	C++
 	CppTests.exe!C4Test::createRev(C4Collection * collection, FLSlice docID, FLSlice revID, FLSlice body, unsigned char flags) Line 357	C++
 	CppTests.exe!ReplicatorLoopbackTest::addRevs(C4Collection * collection, std::chrono::duration<__int64,std::ratio<1,1000000000>> interval, const fleece::alloc_slice & docID, int firstRev, int totalRevs, bool useFakeRevIDs, const char * logName) Line 536	C++
 	CppTests.exe!ReplicatorLoopbackTest::addRevsInParallel::__l2::<lambda_1>::operator()() Line 561	C++
 	CppTests.exe!std::invoke<`ReplicatorLoopbackTest::addRevsInParallel'::`2'::<lambda_1> &>(ReplicatorLoopbackTest::addRevsInParallel::__l2::<lambda_1> & _Obj) Line 1704	C++
 	CppTests.exe!std::_Func_impl_no_alloc<`ReplicatorLoopbackTest::addRevsInParallel'::`2'::<lambda_1>,void>::_Do_call() Line 874	C++
 	CppTests.exe!std::_Func_class<void>::operator()() Line 920	C++
 	CppTests.exe!ReplicatorLoopbackTest::runInParallel::__l2::<lambda_1>::operator()() Line 547	C++
 	CppTests.exe!std::invoke<`ReplicatorLoopbackTest::runInParallel'::`2'::<lambda_1>>(ReplicatorLoopbackTest::runInParallel::__l2::<lambda_1> && _Obj) Line 1704	C++
 	CppTests.exe!std::thread::_Invoke<std::tuple<`ReplicatorLoopbackTest::runInParallel'::`2'::<lambda_1>>,0>(void * _RawVals) Line 61	C++
```

Another thread has taken the lock (CBL Scheduler #4 in this case):

```
>	CppTests.exe!litecore::LogDomain::defaultCallback(const litecore::LogDomain & domain, litecore::LogLevel level, const char * fmt, char * args) Line 559	C++
 	CppTests.exe!logCallback(const litecore::LogDomain & domain, litecore::LogLevel level, const char * fmt, char * args) Line 85	C++
 	CppTests.exe!litecore::LogDomain::vlog(litecore::LogLevel level, const litecore::Logging * logger, bool doCallback, const char * fmt, char * args) Line 463	C++
 	CppTests.exe!litecore::Logging::_logv(litecore::LogLevel level, const char * format, char * args) Line 695	C++
 	CppTests.exe!litecore::Logging::_log(litecore::LogLevel level, const char * format, ...) Line 238	C++
 	CppTests.exe!litecore::repl::Pusher::handleChangesResponse(std::vector<fleece::Retained<litecore::repl::RevToSend>,std::allocator<fleece::Retained<litecore::repl::RevToSend>>> & changes, litecore::blip::MessageIn * reply, bool proposedChanges) Line 266	C++
 	CppTests.exe!litecore::repl::Pusher::sendChanges::__l2::<lambda_1>::operator()(const litecore::blip::MessageProgress & progress) Line 252	C++
 	CppTests.exe!std::invoke<`litecore::repl::Pusher::sendChanges'::`2'::<lambda_1> &,litecore::blip::MessageProgress const &>(litecore::repl::Pusher::sendChanges::__l2::<lambda_1> & _Obj, const litecore::blip::MessageProgress & _Arg1) Line 1714	C++
 	CppTests.exe!std::_Func_impl_no_alloc<`litecore::repl::Pusher::sendChanges'::`2'::<lambda_1>,void,litecore::blip::MessageProgress const &>::_Do_call(const litecore::blip::MessageProgress & <_Args_0>) Line 874	C++
 	CppTests.exe!std::_Func_class<void,litecore::blip::MessageProgress const &>::operator()(const litecore::blip::MessageProgress & <_Args_0>) Line 920	C++
 	CppTests.exe!litecore::repl::Worker::sendRequest::__l5::<lambda_1>::operator()(litecore::blip::MessageProgress progress) Line 120	C++
 	CppTests.exe!std::invoke<`litecore::repl::Worker::sendRequest'::`5'::<lambda_1> &,litecore::blip::MessageProgress>(litecore::repl::Worker::sendRequest::__l5::<lambda_1> & _Obj, litecore::blip::MessageProgress && _Arg1) Line 1714	C++
 	CppTests.exe!std::_Func_impl_no_alloc<`litecore::repl::Worker::sendRequest'::`5'::<lambda_1>,void,litecore::blip::MessageProgress>::_Do_call(litecore::blip::MessageProgress && <_Args_0>) Line 874	C++
 	CppTests.exe!std::_Func_class<void,litecore::blip::MessageProgress>::operator()(litecore::blip::MessageProgress <_Args_0>) Line 920	C++
 	CppTests.exe!std::invoke<std::function<void __cdecl(litecore::blip::MessageProgress)> &,litecore::blip::MessageProgress &>(std::function<void __cdecl(litecore::blip::MessageProgress)> & _Obj, litecore::blip::MessageProgress & _Arg1) Line 1714	C++
 	CppTests.exe!std::_Invoker_ret<std::_Unforced>::_Call<std::function<void __cdecl(litecore::blip::MessageProgress)> &,litecore::blip::MessageProgress &>(std::function<void __cdecl(litecore::blip::MessageProgress)> & _Func, litecore::blip::MessageProgress & <_Vals_0>) Line 2086	C++
 	CppTests.exe!std::_Call_binder<std::_Unforced,0,std::function<void __cdecl(litecore::blip::MessageProgress)>,std::tuple<litecore::blip::MessageProgress>,std::tuple<>>(std::_Invoker_ret<std::_Unforced> __formal, std::integer_sequence<unsigned __int64,0> __formal, std::function<void __cdecl(litecore::blip::MessageProgress)> & _Obj, std::tuple<litecore::blip::MessageProgress> & _Tpl, std::tuple<> && _Ut) Line 2096	C++
 	CppTests.exe!std::_Binder<std::_Unforced,std::function<void __cdecl(litecore::blip::MessageProgress)> &,litecore::blip::MessageProgress &>::operator()<>() Line 2150	C++
 	CppTests.exe!std::invoke<std::_Binder<std::_Unforced,std::function<void __cdecl(litecore::blip::MessageProgress)> &,litecore::blip::MessageProgress &> &>(std::_Binder<std::_Unforced,std::function<void __cdecl(litecore::blip::MessageProgress)> &,litecore::blip::MessageProgress &> & _Obj) Line 1704	C++
 	CppTests.exe!std::_Func_impl_no_alloc<std::_Binder<std::_Unforced,std::function<void __cdecl(litecore::blip::MessageProgress)> &,litecore::blip::MessageProgress &>,void>::_Do_call() Line 874	C++
 	CppTests.exe!std::_Func_class<void>::operator()() Line 920	C++
 	CppTests.exe!litecore::actor::ThreadedMailbox::safelyCall(const std::function<void __cdecl(void)> & f) Line 191	C++
 	CppTests.exe!litecore::actor::ThreadedMailbox::enqueue::__l2::<lambda_1>::operator()() Line 142	C++
 	CppTests.exe!std::invoke<`litecore::actor::ThreadedMailbox::enqueue'::`2'::<lambda_1> &>(litecore::actor::ThreadedMailbox::enqueue::__l2::<lambda_1> & _Obj) Line 1704	C++
 	CppTests.exe!std::_Func_impl_no_alloc<`litecore::actor::ThreadedMailbox::enqueue'::`2'::<lambda_1>,void>::_Do_call() Line 874	C++
 	CppTests.exe!std::_Func_class<void>::operator()() Line 920	C++
 	CppTests.exe!litecore::actor::ThreadedMailbox::performNextMessage() Line 224	C++
 	CppTests.exe!litecore::actor::Scheduler::task(unsigned int taskID) Line 97	C++
 	CppTests.exe!litecore::actor::Scheduler::start::__l15::<lambda_1>::operator()() Line 75	C++
 	CppTests.exe!std::invoke<`litecore::actor::Scheduler::start'::`15'::<lambda_1>>(litecore::actor::Scheduler::start::__l15::<lambda_1> && _Obj) Line 1704	C++
 	CppTests.exe!std::thread::_Invoke<std::tuple<`litecore::actor::Scheduler::start'::`15'::<lambda_1>>,0>(void * _RawVals) Line 61	C++
```

The above thread appears to be stuck waiting to send text to stderr.  Is Catch redirecting stderr and is there some kind of buffer that is getting full I wonder?

```c++
    void LogDomain::defaultCallback(const LogDomain& domain, LogLevel level, const char* fmt, va_list args) {
        char* cstr = nullptr;
        if ( vasprintf(&cstr, fmt, args) < 0 ) throw bad_alloc();
        LogDecoder::writeTimestamp(LogDecoder::now(), cerr);
        LogDecoder::writeHeader(kLevels[(int)level], domain.name(), cerr);
        cerr << cstr << endl; // <----- This line is hanging
        free(cstr);
    }
```

**Comment by snej** [comment]
I came up with some thread-safe macros `Check`, `Require`, `Info` that fall back to our regular `Assert` if called on a background thread.
Didn’t fix Windows, though … same thing that happened to you, the deadlock just happened in a different place (in C4Tests.)
I'm giving up and simply switching to `-r list` when running tests on Windows.

**Comment by snej** [comment]
No idea why Windows failed this time. It was in the middle of running a test and then stopped with `script returned exit code -1`.

**Comment by borrrden** [comment]
That's a time out from the jenkins side that killed it.

**Review by borrrden — APPROVED** [review]

**Pull request merged**
