### PR TITLE
fix memory leak in RevFinder::_findOrRequestRevs

### PR DESCRIPTION
**Pull request by Dushistov**
ref #978

### CODE REVIEW

**Comment by Dushistov** [comment]
This fix memory leak for me,
because of `vector<C4StringResult> ancestors(nChanges)` = `vector<FLSliceResult>`,
is type without destructor, so it should be freed manually. 
And converting to alloc_slice is nice way to free memory,
but should be used  `alloc_slice(FLSliceResult &&)`
instead of `alloc_slice(const FLSliceResult &)`.

This is done in the supposition that there is no exception possible in the 
`for (size_t i = 0; i < nChanges; ++i) {`,
if exception possible may be better convert `vector<C4StringResult> ancestors` to `vector<alloc_slice>` right after `c4db_findDocAncestors` call.

**Comment by borrrden** [comment]
An elegant way to tackle this!  And to your point about exceptions, as a rule our C API functions are all `noexcept` (especially the public ones, since they serve as a bridge to other languages that have no way of dealing with native exceptions).  If there is a possibility for an error condition then the function will have a `C4Error *` parameter that will capture the error information.  I'm going to discuss about how to handle this situation more explicitly and then decide on this PR.

**Comment by Dushistov** [comment]
> as a rule our C API functions are all noexcept

but all functions inside loop is not C API functions and not marked as noexcept
```
 _db->setDocRemoteAncestor(docID, revID);
 replicator()->docRemoteAncestorChanged(docID, revID);
```
So, if for example `nChanges == 2`, and exception will occur during the first element handling,
then memory leak happens.

**Comment by snej** [comment]
Thanks @Dushistov, that's a good fix ... I'll look at the surrounding code to see if there could be an exception in that loop.

**Comment by snej** [comment]
Exceptions won't be an issue in that loop. The replicator code tends to use `C4Error*` rather than throw exceptions.

**Pull request merged**
