### PR TITLE
Return null-padded C4StringResults for error messages

### PR DESCRIPTION
**Pull request by snej**
The slice doesn't contain the 0 byte; rather, the 0 is one byte past the end. But it's a valid C string including that byte.

Also changed C4SliceResult to C4StringResult in some APIs, which has no effect on code but clarifies that these slices contain text, not binary data.

### CODE REVIEW

**Comment by borrrden** [comment]
@pasin I remember an awkward reason for making this fix but I can't remember what it was.  Did it have something to do with C?

**Comment by pasin** [comment]
IIRC We had some discussion in slack about using CBL-C API that returns String as Slice but the Slice doesn't have null padding so it needs to be copied.

**Comment by borrrden** [comment]
I'm interested in finding out where this is used.

**Comment by jianminzhao** [comment]
Returning nullPaddedString() as C4StringResult for some APIs may be confusing. After consulting with Jens, I close it.

**Pull request closed without merging**
