### PR TITLE
Ref-counting optimizations

### PR DESCRIPTION
**Pull request by snej**
* Updated Fleece: Some micro-optimizations for moving a Retained, and turning a Retained in a a bare pointer with a reference.
* Tweaked some LiteCore code to eliminate a retain+release where the Retained-to-pointer optimization can be applied.

### CODE REVIEW

**Comment by snej** [comment]
"REST DELETE database" test failed on Jenkins. Is this a flaky test?

**Comment by borrrden** [comment]
Not to my knowledge.  I rarely see failures in REST but in the past weeks I've seen them popping up....

**Comment by borrrden** [comment]
The test didn't fail, the job timed out.

**Comment by borrrden** [comment]
I retriggered the job and it passed.

**Review by borrrden — APPROVED** [review]

**Pull request merged**
