### PR TITLE
Fixes for Windows (and possibly other non-Apple)

### PR DESCRIPTION
**Pull request by borrrden**
Dependent on https://github.com/couchbaselabs/BLIP-Cpp/pull/1 and https://github.com/couchbaselabs/fleece/pull/16

Most of the commit here is C# stuff, but there are a few things in C++ (notably, Windows complains about the ambiguity between fleece::slice and litecore::blip::slice despite them being the same thing)

### CODE REVIEW

**Comment by snej** [comment]
The slice ambiguity is strange. Could you show me what the compile errors look like?

**Comment by borrrden** [comment]
That's literally the message. It says slice is ambiguous between those two types. I will paste the exact message when I get back to my machine later

**Comment by borrrden** [comment]
> D:\Development\couchbase-lite-net-2\vendor\couchbase-lite-core\Replicator\c4Replicator.cc(141): error C2872: 'slice': ambiguous symbol
> D:\Development\couchbase-lite-net-2\vendor\couchbase-lite-core\vendor\fleece\Fleece\slice.hh(147): note: could be 'fleece::slice'
> d:\development\couchbase-lite-net-2\vendor\couchbase-lite-core\vendor\blip-cpp\include\blip_cpp\Message.hh(29): note: or       'litecore::blip::slice'

**Comment by snej** [comment]
I'll try to get around the so-called ambiguity so we don't have to spell out the namespaces here. I think the `using` declaration in Message.hh is the culprit; I thought its effect would only be local to the enclosing `namespace{...}` block, but I guess not.

**Pull request merged**
