### PR TITLE
Fix logic error in c4coll_isIndexTrained

### PR DESCRIPTION
**Pull request by borrrden**
It was universally returning true.  Also remove the warnings check from the VS test since it makes no sense anymore and is really hard to in the isTrained test now that "untrained" is a warning.  Add in a test for the C API to make sure it works correctly.

### CODE REVIEW

**Review by pasin — APPROVED** [review]

**Comment by pasin** [comment]
Build failed in PR validation.

**Review by jianminzhao — APPROVED** [review]

**Comment by jianminzhao** [comment]
[CBL-5906](https://issues.couchbase.com/browse/CBL-5906)
I think this PR does the above. Please confirm.

**Comment by borrrden** [comment]
Yes, I didn't know there was a ticket for that.  I added those checks in.

**Comment by snej** [comment]
I disagree about removing the warnings check; I think it's useful. And I have a separate PR where I fixed the tests by correctly setting the number of expected warnings. Could you take that out of this PR, and we can decide whether or not to do it?

**Comment by borrrden** [comment]
Needing to know how many warnings are logged in order for a test to succeed is really quite obnoxious though.  If I take it out of here I need a system of incrementing the expected warnings count by the number of sections since the check only resets at the end of the test....

**Comment by borrrden** [comment]
Or maybe I'm hallucinating?  I seem to have put the increment in the correct place this time and the test is ok with it.

**Review by snej — APPROVED** [review]

**Pull request merged**
