### PR TITLE
Update Android NDK to 23b

### PR DESCRIPTION
**Pull request by borrrden**
In the process it was determined that we need to move to a stock CMake and Ninja, so fetch those from cbdeps

### CODE REVIEW

**Comment by borrrden** [comment]
macOS test failure unrelated to this PR

**Comment by bmeike** [comment]
Is there a branch I can check out, to see if this affects me at all.  I'm pretty sure it does not, but I'd like to be able to  verify that.

.... and sorry to be so long about looking at this.  I didn't realize until today that it was waiting on me.

**Comment by borrrden** [comment]
A branch you can check out, yes, but I am guessing that is not what you mean?  Do you mean that you want a prebuilt artifact to test with?  The branch name is at the top of this PR:

`feature/cbl-2943_bump_ndk`

**Comment by bmeike** [comment]
Yeah... I could work with just the branch... but if you have artifacts that would let me get to it more quickly...

**Comment by bmeike** [comment]
I am about to commit a change that will have Android building with exactly the same tool chain.  This should be good to go.

**Review by bmeike — APPROVED** [review]
👍🏻

**Pull request merged**
