### PR TITLE
feat: update fleece submodule

### PR DESCRIPTION
**Pull request by jayahariv**
* include fleece latest leak fixes
* API change updated in lite core (FLSliceResult_Free -> FLSliceResult_Release)

### CODE REVIEW

**Comment by jayahariv** [comment]
create predictive index is failing
```
libc++abi.dylib: terminating with uncaught exception of type fleece::FleeceException: invalid input data: Can't retain immutable Value 0x6070002696a8 that's not part of a Doc
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00007fff6903b47a libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00000001061c1243 libsystem_pthread.dylib`pthread_kill + 384
    frame #2: 0x00007fff68fc3a08 libsystem_c.dylib`abort + 120
    frame #3: 0x00007fff6608dbc8 libc++abi.dylib`abort_message + 231
    frame #4: 0x00007fff6608dd64 libc++abi.dylib`demangling_terminate_handler() + 238
    frame #5: 0x00007fff67b8fab2 libobjc.A.dylib`_objc_terminate() + 104
    frame #6: 0x00007fff6609ada7 libc++abi.dylib`std::__terminate(void (*)()) + 8
    frame #7: 0x00007fff6609ad59 libc++abi.dylib`std::terminate() + 41
    frame #8: 0x000000010001568f LiteCoreCppTests`__clang_call_terminate + 15
  * frame #9: 0x00000001020e53af LiteCoreCppTests`fleece::impl::Array const* fleece::retain<fleece::impl::Array const>(r=0x00006070002696a8) at RefCounted.hh:70:19
    frame #10: 0x00000001020d99e7 LiteCoreCppTests`fleece::RetainedConst<fleece::impl::Array>::operator=(this=0x0000604000afddb8, t=0x00006070002696a8) at RefCounted.hh:161:20
    frame #11: 0x00000001020d94e5 LiteCoreCppTests`fleece::impl::internal::HeapArray::HeapArray(this=0x0000604000afdd90, a=0x00006070002696a8) at HeapArray.cc:40:25
    frame #12: 0x00000001020d9b27 LiteCoreCppTests`fleece::impl::internal::HeapArray::HeapArray(this=0x0000604000afdd90, a=0x00006070002696a8) at HeapArray.cc:33:5
    frame #13: 0x000000010210f5ec LiteCoreCppTests`fleece::impl::MutableArray::newArray(a=0x00006070002696a8, flags=kDefaultCopy) at MutableArray.hh:28:36
    frame #14: 0x0000000100d35202 LiteCoreCppTests`litecore::SQLiteKeyStore::createPredictiveIndex(this=0x00006120001cc6c0, spec=0x00000001091e0860, expressions=0x00006070002696b2, options=0x0000000000000000) at SQLiteKeyStore+PredictiveIndexes.cc:47:21
    frame #15: 0x0000000100c59ead LiteCoreCppTests`litecore::SQLiteKeyStore::createIndex(this=0x00006120001cc6c0, spec=0x00000001091e0860, options=0x0000000000000000) at SQLiteKeyStore+Indexes.cc:78:45
    frame #16: 0x0000000100e9767a LiteCoreCppTests`litecore::KeyStore::createIndex(this=0x00006120001cc6c0, name=slice @ 0x00000001091e0820, expressionJSON=slice @ 0x00000001091e0840, type=kPredictiveIndex, options=0x0000000000000000) at KeyStore.cc:79:16
    frame #17: 0x000000010089d5ff LiteCoreCppTests`(anonymous namespace)::____C_A_T_C_H____T_E_S_T____141::test(this=0x00000001090132a0) at PredictiveQueryTest.cc:145:12
    frame #18: 0x000000010090901d LiteCoreCppTests`Catch::MethodTestCase<(anonymous namespace)::____C_A_T_C_H____T_E_S_T____141>::invoke(this=0x00006030000371e0) const at catch.hpp:650:9
    frame #19: 0x000000010001ce1a LiteCoreCppTests`Catch::TestCase::invoke(this=0x000062e00001e280) const at catch.hpp:7519:15
    frame #20: 0x00000001000a5627 LiteCoreCppTests`Catch::RunContext::invokeActiveTestCase(this=0x000000010933d8a0) at catch.hpp:6158:31
    frame #21: 0x00000001000a398c LiteCoreCppTests`Catch::RunContext::runCurrentTest(this=0x000000010933d8a0, redirectedCout="", redirectedCerr="") at catch.hpp:6129:21
    frame #22: 0x000000010000988e LiteCoreCppTests`Catch::RunContext::runTest(this=0x000000010933d8a0, testCase=0x000062e00001e280) at catch.hpp:5949:21
    frame #23: 0x0000000100006d67 LiteCoreCppTests`Catch::runTests(config=0x0000000109222928) at catch.hpp:6297:35
    frame #24: 0x0000000100141d82 LiteCoreCppTests`Catch::Session::run(this=0x0000000109222820) at catch.hpp:6405:42
    frame #25: 0x00000001000405d8 LiteCoreCppTests`Catch::Session::run(this=0x0000000109222820, argc=4, argv=0x00007ffeefbff480) at catch.hpp:6384:30
    frame #26: 0x000000010004035c LiteCoreCppTests`main(argc=4, argv=0x00007ffeefbff480) at catch.hpp:10333:29
    frame #27: 0x00007fff68eec405 libdyld.dylib`start + 1
(lldb) 
```

**Comment by snej** [comment]
I'll take a look at the exception...

**Comment by snej** [comment]
I fixed this on the dev branch last month in commit 608b76a. You should be able to cherry-pick that to master.

**Comment by jayahariv** [comment]
Failure in ReplicatorLoopbackTest > "Delta Push+Push"
```
FAILED ASSERTION `scope->_isDoc` in static RetainedConst<fleece::impl::Doc> fleece::impl::Doc::containing(const fleece::impl::Value *) (at Doc.cc line 304)
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 2.1
    frame #0: 0x00007fff6608c2de libc++abi.dylib`__cxa_throw
    frame #1: 0x0000000102075e89 LiteCoreCppTests`fleece::_assert_failed(condition="scope->_isDoc", fn="static RetainedConst<fleece::impl::Doc> fleece::impl::Doc::containing(const fleece::impl::Value *)", file="Doc.cc", line=304) at betterassert.cc:36:9
  * frame #2: 0x00000001021c855c LiteCoreCppTests`fleece::impl::Doc::containing(src=0x00006120007466d0) at Doc.cc:304:9
    frame #3: 0x000000010222e4ed LiteCoreCppTests`fleece::impl::internal::HeapValue::retain(v=0x00006120007466d0) at HeapValue.cc:148:38
    frame #4: 0x000000010219303a LiteCoreCppTests`fleece::impl::Value::_retain(this=0x00006120007466d0) const at Value.cc:423:38
    frame #5: 0x00000001020b11d5 LiteCoreCppTests`fleece::impl::Dict const* fleece::retain<fleece::impl::Dict const>(r=0x00006120007466d0) at RefCounted.hh:70:19
    frame #6: 0x000000010207a587 LiteCoreCppTests`fleece::RetainedConst<fleece::impl::Dict>::operator=(this=0x000060c001540018, t=0x00006120007466d0) at RefCounted.hh:161:20
    frame #7: 0x0000000102079910 LiteCoreCppTests`fleece::impl::internal::HeapDict::HeapDict(this=0x000060c001540000, d=0x00006120007466d0) at HeapDict.cc:40:25
    frame #8: 0x000000010207a867 LiteCoreCppTests`fleece::impl::internal::HeapDict::HeapDict(this=0x000060c001540000, d=0x00006120007466d0) at HeapDict.cc:31:5
    frame #9: 0x00000001021109ac LiteCoreCppTests`fleece::impl::MutableDict::newDict(d=0x00006120007466d0, flags=3) at MutableDict.hh:19:36
    frame #10: 0x00000001020f79a6 LiteCoreCppTests`_newMutableDict(d=0x00006120007466d0, flags=kFLDeepCopyImmutables) at Fleece.cc:351:37
    frame #11: 0x00000001020f7b46 LiteCoreCppTests`::FLDict_MutableCopy(d=0x00006120007466d0, flags=kFLDeepCopyImmutables) at Fleece.cc:361:16
    frame #12: 0x0000000100bcc7ef LiteCoreCppTests`fleece::Dict::mutableCopy(this=0x000000010912aa20, flags=kFLDeepCopyImmutables) const at Mutable.hh:239:28
    frame #13: 0x0000000100bcc4cc LiteCoreCppTests`mutateDoc(this=0x000000010911bc68, props=Dict @ 0x000000010912aa20, enc=0x00007ffeefbfd4b0)>)::$_5::operator()(fleece::Dict, fleece::Encoder&) const at ReplicatorLoopbackTest.cc:1414:38
    frame #14: 0x0000000100bcc23e LiteCoreCppTests`decltype(__f=0x000000010911bc68, __args=0x0000000108efa860, __args=0x00007ffeefbfd4b0)>)::$_5&>(fp)(std::__1::forward<fleece::Dict>(fp0), std::__1::forward<fleece::Encoder&>(fp0))) std::__1::__invoke<mutateDoc(c4Database*, fleece::slice, std::__1::function<void (fleece::MutableDict)>)::$_5&, fleece::Dict, fleece::Encoder&>(mutateDoc(c4Database*, fleece::slice, std::__1::function<void (fleece::MutableDict)>)::$_5&, fleece::Dict&&, fleece::Encoder&) at type_traits:4361:1
    frame #15: 0x0000000100bcbe99 LiteCoreCppTests`void std::__1::__invoke_void_return_wrapper<void>::__call<mutateDoc(__args=0x000000010911bc68, __args=0x0000000108efa860, __args=0x00007ffeefbfd4b0)>)::$_5&, fleece::Dict, fleece::Encoder&>(mutateDoc(c4Database*, fleece::slice, std::__1::function<void (fleece::MutableDict)>)::$_5&, fleece::Dict&&, fleece::Encoder&) at __functional_base:349:9
    frame #16: 0x0000000100bcbced LiteCoreCppTests`std::__1::__function::__alloc_func<mutateDoc(c4Database*, fleece::slice, std::__1::function<void (fleece::MutableDict)>)::$_5, std::__1::allocator<mutateDoc(c4Database*, fleece::slice, std::__1::function<void (fleece::MutableDict)>)::$_5>, void (fleece::Dict, fleece::Encoder&)>::operator(this=0x000000010911bc68, __arg=0x0000000108efa860, __arg=0x00007ffeefbfd4b0)(fleece::Dict&&, fleece::Encoder&) at functional:1527:16
    frame #17: 0x0000000100bc55aa LiteCoreCppTests`std::__1::__function::__func<mutateDoc(c4Database*, fleece::slice, std::__1::function<void (fleece::MutableDict)>)::$_5, std::__1::allocator<mutateDoc(c4Database*, fleece::slice, std::__1::function<void (fleece::MutableDict)>)::$_5>, void (fleece::Dict, fleece::Encoder&)>::operator(this=0x000000010911bc60, __arg=0x0000000108efa860, __arg=0x00007ffeefbfd4b0)(fleece::Dict&&, fleece::Encoder&) at functional:1651:12
    frame #18: 0x0000000100bc3c0c LiteCoreCppTests`std::__1::__function::__value_func<void (fleece::Dict, fleece::Encoder&)>::operator(this=0x000000010911bc60, __args=0x0000000108efa860, __args=0x00007ffeefbfd4b0)(fleece::Dict&&, fleece::Encoder&) const at functional:1799:16
    frame #19: 0x0000000100bc3902 LiteCoreCppTests`std::__1::function<void (fleece::Dict, fleece::Encoder&)>::operator(this=0x000000010911bc60, __arg=Dict @ 0x0000000108efa860, __arg=0x00007ffeefbfd4b0)(fleece::Dict, fleece::Encoder&) const at functional:2347:12
    frame #20: 0x0000000100bc2540 LiteCoreCppTests`mutateDoc(db=0x00006120001a2840, docID=slice @ 0x00007ffeefbfd120, mutator=function<void (fleece::Dict, fleece::Encoder &)> @ 0x000000010911bc60)>) at ReplicatorLoopbackTest.cc:1396:5
    frame #21: 0x0000000100bc15cd LiteCoreCppTests`mutateDoc(db=0x00006120001a2840, docID=slice @ 0x000000010911bc20, mutator=function<void (fleece::MutableDict)> @ 0x000000010911ba80)>) at ReplicatorLoopbackTest.cc:1413:5
    frame #22: 0x0000000100bc0ed4 LiteCoreCppTests`mutationsForDelta(db=0x00006120001a2840) at ReplicatorLoopbackTest.cc:1425:9
    frame #23: 0x0000000100af3416 LiteCoreCppTests`(anonymous namespace)::____C_A_T_C_H____T_E_S_T____1434::test(this=0x0000000109320020) at ReplicatorLoopbackTest.cc:1445:5
    frame #24: 0x0000000100c44fc5 LiteCoreCppTests`Catch::MethodTestCase<(anonymous namespace)::____C_A_T_C_H____T_E_S_T____1434>::invoke(this=0x000060300003aff0) const at catch.hpp:650:9
    frame #25: 0x000000010001ccda LiteCoreCppTests`Catch::TestCase::invoke(this=0x000062e000022780) const at catch.hpp:7519:15
    frame #26: 0x00000001000a54e7 LiteCoreCppTests`Catch::RunContext::invokeActiveTestCase(this=0x000000010933d8a0) at catch.hpp:6158:31
    frame #27: 0x00000001000a384c LiteCoreCppTests`Catch::RunContext::runCurrentTest(this=0x000000010933d8a0, redirectedCout="", redirectedCerr="") at catch.hpp:6129:21
    frame #28: 0x000000010000974e LiteCoreCppTests`Catch::RunContext::runTest(this=0x000000010933d8a0, testCase=0x000062e000022780) at catch.hpp:5949:21
    frame #29: 0x0000000100006c27 LiteCoreCppTests`Catch::runTests(config=0x0000000109222928) at catch.hpp:6297:35
    frame #30: 0x0000000100141c42 LiteCoreCppTests`Catch::Session::run(this=0x0000000109222820) at catch.hpp:6405:42
    frame #31: 0x0000000100040498 LiteCoreCppTests`Catch::Session::run(this=0x0000000109222820, argc=4, argv=0x00007ffeefbff480) at catch.hpp:6384:30
    frame #32: 0x000000010004021c LiteCoreCppTests`main(argc=4, argv=0x00007ffeefbff480) at catch.hpp:10333:29
    frame #33: 0x00007fff68eec405 libdyld.dylib`start + 1
(lldb) 
```

**Comment by snej** [comment]
I think we should avoid bringing in those other Fleece commits, this late in the release cycle. (I shouldn't have put them on the master branch, probably...)
Just create a `release/mercury` branch at the previous Fleece commit LiteCore was using, and cherry-pick the leak fixes onto that branch.

**Comment by jayahariv** [comment]
Closing and will open more simpler PR

**Pull request closed without merging**
