### PR TITLE
CBL-3669: Change occurrences of sprintf to snprintf

### PR DESCRIPTION
**Pull request by callumbirks**

### CODE REVIEW

**Comment by borrrden** [comment]
Unassigning until the validation failures are fixed

**Comment by callumbirks** [comment]
What's the reason the build and tests would be passing fine on my machine but failing here, are there things that aren't built by default locally that I can enable to make sure everything is building fine? @borrrden

**Comment by callumbirks** [comment]
Nevermind, I think I figured it out. I was only building the C++ tests before. Selecting the C Tests scheme showed me the other errors that weren't showing up before.

**Review by pasin — APPROVED** [review]

**Comment by borrrden** [comment]
Don't merge this just yet, I want to include the Fleece changes as well.

**Pull request merged**
