### PR TITLE
CBL-4330: Add Clang-Format to GH Actions

### PR DESCRIPTION
**Pull request by callumbirks**
Re-open of PR because Jenkins MacOS build & test was consistently failing a certificates test.

### CODE REVIEW

**Comment by callumbirks** [comment]
To re-iterate, formatting is now being run on `MSVC/` folder also, so this PR includes those changes. This also includes some additional small formatting changes. 
As the linter is now in actions (as of this PR being merged), I will recommend everyone run formatting after every local change/commit. This can be done either via the shell script (`./build_cmake/scripts/run-clang-format.sh`) or via Building against the "Run Clang-Format" target in Xcode. 
@borrrden if you like I will also throw something together for Windows.

**Comment by callumbirks** [comment]
The change is growing as there have been a few PRs without formatting applied, so that formatting has to happen here (otherwise the Linter will not pass).

**Review by borrrden — APPROVED** [review]
Beautiful!

**Comment by jianminzhao** [comment]
"Run Clang-Format"  - how to run this target?

**Review by jianminzhao — APPROVED** [review]

**Comment by callumbirks** [comment]
> "Run Clang-Format" - how to run this target?

@jianminzhao Select the scheme, then Build (CMD+B). Not the nicest solution, but at least makes it accessible from GUI. If you prefer terminal you can just `./build_cmake/scripts/run-clang-format.sh`

**Pull request merged**
