### PR TITLE
Make JSON query to look the same as the N1QL in terms of operator vs …

### PR DESCRIPTION
**Pull request by jianminzhao**
…function. #CBL-1823

['IS_VALUED()', ...] --> ['IS VALUED', ...]
['META', ...] --> ['META()', ...]

### CODE REVIEW

**Comment by borrrden** [comment]
This is another change that is going to affect the platforms!  Is this necessary?

**Comment by jianminzhao** [comment]
These two functions/operators are all new.

**Comment by borrrden** [comment]
There is currently a way to get meta data in the JSON query syntax though.  Doesn't this change it?

**Comment by jianminzhao** [comment]
No. I did not remove the existing method to address the meta properties, like "_id". @snej was suggesting to keep existing method intact for the time being. I guess there would be many meta things in the current query builder and we need to cooperate to remove old method.

**Review by borrrden — APPROVED** [review]

**Pull request merged**
