### PR TITLE
CBL-127: Conflict error in CBL P2P push replication when using differ…

### PR DESCRIPTION
**Pull request by jianminzhao**
…ent target database UID

The problem has been taken care of by the new property, "conflictIncludesRev", introduced by the resolution of CBL 2637, to the BLIP message "proposeChanges". We added test case to verify it.

### CODE REVIEW

**Review by callumbirks — APPROVED** [review]

**Comment by jianminzhao** [comment]
I originally tried to verify that the test hit the targeted code path by the following means,
    {
        catchLog::savedCB       = c4log_getCallback();
        C4LogLevel savedCBLevel = c4log_callbackLevel();
        catchLog::logs.reset(new vector<string>);
        c4log_writeToCallback(kC4LogInfo, catchLog::logCB, true);

        DEFER {
            catchLog::logs.reset(nullptr);
            c4log_writeToCallback(savedCBLevel, catchLog::savedCB, false);
            catchLog::savedCB = nullptr;
        };

        ......

        std::regex regex{R"(Rejecting proposed change .* \(status 409; current rev is .*\))"};
        bool       found409 = false;
        for ( auto& s : *catchLog::logs.get() ) {
            std::smatch sm;
            if ( std::regex_search(s, sm, regex) ) { found409 = true; }
        }
        if ( toDifferentTarget ) {
            // Pusher receives 409 error with different target. It then send a new "proposedChange" as
            // it recognizes the revision that the error response includes and ends up with the same
            // result.
            CHECK(found409);
        } else {
            CHECK_FALSE(found409);
        }
    }
but Windows does not like it.

**Review by borrrden — APPROVED** [review]
I'm assuming you observed this new message happen, or saw this test fail in an older commit.

**Comment by jianminzhao** [comment]
yes, saw it failed a couple times before I decided Windows just did not like it. My request of VS 17 2022 is still pending at Zendesk, and I cannot try it on my local machine.

**Comment by borrrden** [comment]
I meant the new BLIP message, not the error message.

**Comment by jianminzhao** [comment]
For the blip message, I observed in Xcode by manually turning the BLIPMessage log to Debug

**Pull request merged**
