### PR TITLE
Fix SQLiteCpp pointing to an orphaned commit

### PR DESCRIPTION
**Pull request by callumbirks**
release/3.1 is suddenly pointing to an orphaned commit, breaking all Helium builds.
With this PR I'm pointing it back to the correct commit on `2.0.0-couchbase`.
@jianminzhao I think this might be related to your recent breaking and subsequent fixing of the SQLiteCpp pointing to the wrong branch? Could you confirm.

### CODE REVIEW

**Comment by callumbirks** [comment]
Ignoring blackduck failure. It's failing because of the orphaned commit

**Review by pasin — COMMENTED** [review]
Is the check_bd_versions.py ported from the other branch?

**Comment by callumbirks** [comment]
> Is the check_bd_versions.py ported from the other branch?

@pasin the script was originally changed with the change which broke the SqLiteCpp branching rules. It seemed to be failing, so I reverted the script back to what it used to be.
I think the changes in the script supported Jianmin's changing away from the `2.0.0-couchbase`, but maybe @jianminzhao can also comment on that.

**Comment by jianminzhao** [comment]
Yes, the deletion of that branch is the cause of the first failure of submodule check.
Now that you pointed it to 90a4aae0238, which is headed by 2.0.0-couchbase, the problem is rectified.

"might be related to your recent breaking and subsequent fixing of the SQLiteCpp pointing to the wrong branch? Could you confirm" - the "recent breaking" is not breaking of the build. It was the the commit that SQLiteCpp was not the one supposed to be. After making 3.2 & 3.3 pointing to 2.0.0-couchbase, we over did it with deletion of that branch.

The current failure of BD check, I think, is because the version is changed between 3.43.0 and 3.45.0. 
I don't know why you had to change the script, check_bd_versions

**Comment by callumbirks** [comment]
@jianminzhao the version is not changed. It is 3.43.0, which it was before. 3.1 still points to the same "commit" with this PR, it's just on a different branch so has different commit hash.

I think the BD failure seems to be it cannot compare with the orphaned commit

**Review by pasin — APPROVED** [review]
Assume that the duck script is correct.

**Comment by callumbirks** [comment]
@jianminzhao thanks, that script looks nicely improved! Is this ready to be merged now?

**Comment by jianminzhao** [comment]
Agree with @callumbirks the failure of bd check is due to orphaned commit that SQLiteCpp references has been garbage collected. In theory, there is no way to restore it updated the script to recognize the issue and request manual verification.

**Comment by callumbirks** [comment]
@jianminzhao reviewed the changed script. LGTM and seems to be reflected in the output of the "Check Blackduck Manifest" check.

**Pull request merged**
