### PR TITLE
CBL-5634 (Fix): ReplacementRev puller enhancement

### PR DESCRIPTION
**Pull request by callumbirks**

### CODE REVIEW

**Comment by callumbirks** [comment]
Turns out I had misread the spec before. "replacedRev" contains the revID of the rev we originally requested. "rev" still contains the revID of the rev we are being sent, whether or not it is a replacementRev.
See the testing I've done for this in this PR: #2021

**Comment by callumbirks** [comment]
Whoops I caught my keyboard and it assigned CBL-bot somehow 😆

**Review by pasin — APPROVED** [review]

**Review by pasin — APPROVED** [review]
As chatted before, we should add some log showing the replacement rev and replaced rev.

**Comment by callumbirks** [comment]
@pasin I've added a log.
It will be for example
> Received revision 'doc1' #2-ff (seq '1') (replaced rev #1-ff)

**Pull request merged**
