### PR TITLE
Clone the QueryEnumerator before passing it to the QueryObserver call…

### PR DESCRIPTION
**Pull request by jianminzhao**
…back. CBL-2460

### CODE REVIEW

**Comment by pasin** [comment]
Seem like the test is hitting CBL-2459.

**Comment by borrrden** [comment]
> 
> 
> Seem like the test is hitting [CBL-2459](https://issues.couchbase.com/browse/CBL-2459).

Is this an intermittent issue?  The test passed on GH actions

**Comment by pasin** [comment]
There is a race. If the second observer is added after the first observer is notified, the second observer will not be notified until there is a change.

**Comment by jianminzhao** [comment]
yes, I noticed this too. I did not mean to solve this problem (or not.a problem)

**Pull request merged**
