### PR TITLE
Adjust the SGW config to work with SGW3.0, CBL-2254

### PR DESCRIPTION
**Pull request by jianminzhao**

### CODE REVIEW

**Review by borrrden — APPROVED** [review]
I noticed that adding these removes the ability to start up with 2.8.x.  As long as that's ok.

**Review by JRascagneres — APPROVED** [review]
Looks fine to me. As Jim stated though this won't work for 2.8.x anymore. 
These options are also possible to pass in as command line flags if that suits you better? Otherwise this should work :)

**Comment by jianminzhao** [comment]
@borrrden @pasin how about to change the current config.json to config_2.8.json? Or just overwrite it. If in some case we need to run sgw 2.8, we can always get the previous version from git. What is you opnion?

**Review by pasin — APPROVED** [review]

**Comment by pasin** [comment]
IMO, as SGW 2.8 will be around for quite some time. It's good to have a backup for 2.8 config.

**Comment by jianminzhao** [comment]
I added a tag to 2.8 config. "git show sgw2.8-config" will print the config.json for 2.8 sgw

**Pull request merged**
